sudo: required

language: cpp

env:
  matrix:
    - OS_TYPE=centos OS_VERSION=6
#    - OS_TYPE=centos OS_VERSION=7

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - docker pull gitlab-registry.cern.ch/sturdy/gemdaq_ci_worker:slc6
  - docker ps -a

script:
  - uname -a
  - ls -lshtar
  - which yum
#  - yum list installed
